ALTER TABLE `User` MODIFY `role` ENUM('SUPER_ADMIN', 'ADMIN', 'EDITOR', 'STAFF') NOT NULL DEFAULT 'STAFF';

UPDATE `User`
SET `role` = 'SUPER_ADMIN'
WHERE `role` = 'ADMIN';

UPDATE `User`
SET `role` = 'STAFF'
WHERE `role` = 'EDITOR';

ALTER TABLE `User` MODIFY `role` ENUM('SUPER_ADMIN', 'ADMIN', 'STAFF') NOT NULL DEFAULT 'STAFF';
